#file: noinspection KubernetesUnknownValues
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-batch-init
data:
  init-vector.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    ALTER EXTENSION vector SET SCHEMA public;

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-batch
  labels:
    app: postgres-batch
spec:
  serviceName: "postgres-batch-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-batch
  template:
    metadata:
      labels:
        app: postgres-batch
        purpose: batch-test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
        fluentbit.io/exclude: "true"
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: ${NODE_SELECTOR}
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-batch-secret
          resources:
            requests:
              ephemeral-storage: "2Gi"
              memory: "1Gi"
              cpu: "500m"
            limits:
              ephemeral-storage: "4Gi"
              memory: "2.5Gi"
              cpu: "1500m"
          volumeMounts:
            - name: postgres-batch-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - "pg_ctl stop -D /var/lib/postgresql/data/postgres -m fast"
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  key: DATA_SOURCE_NAME
                  name: postgres-batch-secret
            - name: PG_EXPORTER_DISABLE_DEFAULT_METRICS
              value: "false"
            - name: PG_EXPORTER_DISABLE_SETTINGS_METRICS
              value: "false"
          ports:
            - containerPort: 9187
              name: metrics
          resources:
            limits:
              ephemeral-storage: 256Mi
              cpu: 200m
              memory: 128Mi
            requests:
              ephemeral-storage: 128Mi
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-batch-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-batch-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 40Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-batch-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-batch
  ports:
    - port: 5432
      targetPort: 5432
