#file: noinspection SpellCheckingInspection
spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 3s

  kafka:
    bootstrap-servers: localhost:9092

client:
  commerce: http://localhost:8087
