apiVersion: batch/v1
kind: Job
metadata:
  name: group-purchase-job
  labels:
    app: batch
    component: job
    job-type: group-purchase
    purpose: batch-test
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  activeDeadlineSeconds: 3600
  template:
    metadata:
      labels:
        app: batch
        job-type: group-purchase
        purpose: batch-test
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: ${NODE_SELECTOR}
      containers:
      - name: batch-job
        image: minbros/batch:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: TZ
          value: "Asia/Seoul"
        - name: SPRING_BATCH_JOB_NAME
          value: "groupPurchaseJob"
        - name: JOB_DESCRIPTION
          value: "공구 상태 업데이트 작업 (배치 테스트)"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-batch-service:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-batch-service:5432/postgres"
        - name: ELASTICSEARCH_URIS
          value: "http://elasticsearch-service:9200"
        envFrom:
          - secretRef:
              name: batch-secret
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "1500m"
            ephemeral-storage: "3Gi"
