dependencies {
    /* === Web */
    implementation 'org.springframework.boot:spring-boot-starter-web'

    /* === JPA / DB === */
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'       // PostgreSQL 드라이버

    //common 모듈
    implementation project(':common')

    //도메인 의존성 추가
    implementation(project(path: ':member', configuration: 'domainElements'))
    implementation(project(path: ':commerce', configuration: 'domainElements'))
    implementation(project(path: ':point', configuration: 'domainElements'))
    implementation 'org.jeasy:easy-random-core:5.0.0'

    //Easy Random
    implementation 'org.jeasy:easy-random-core:5.0.0'

    testImplementation 'org.springframework.security:spring-security-test'

    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:junit-jupiter'

    jib {
        from {
            image = 'eclipse-temurin:17-jre'
        }
    }
}

bootJar {
    enabled = true
}
