package store._0982.member.domain.notification;

public enum NotificationType {
    ORDER_SCHEDULED,
    ORDER_COMPLETED,
    ORDER_FAILED,
    POINT_RECHARGED,
    POINT_DEDUCTED,
    POINT_RETURNED,
    GROUP_PURCHASE_COMPLETED,
    GROUP_PURCHASE_FAILED,
    DAILY_SETTLEMENT_COMPLETED,
    DAILY_SETTLEMENT_FAILED,
    MONTHLY_SETTLEMENT_COMPLETED,
    MONTHLY_SETTLEMENT_FAILED
}
