dependencies {
    // 필요한 의존성 추가
    implementation project(':common')

    //openfeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    //DB
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:postgresql:1.20.4'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.4'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'

    // Spring Retry
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'

    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // H2 Database for testing
    testRuntimeOnly 'com.h2database:h2'

    // Spring Cloud OpenFeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // AWS S3
    implementation 'software.amazon.awssdk:s3:2.25.0'
    implementation "software.amazon.awssdk:auth"
}

bootJar {
    enabled = true
}

jib {
    from {
        image = 'eclipse-temurin:17-jre'
    }
    container {
        ports = ['8087']
    }
}

tasks.register('domainJar', Jar) {
    archiveClassifier = 'domain'
    from(sourceSets.main.output) {
        include 'store/_0982/commerce/domain/**'
    }
    dependsOn classes
}

configurations {
    domainElements {                       // 도메인 전용 소비용 구성
        canBeConsumed = true               // 다른 모듈에서 가져올 수 있게
        canBeResolved = false              // 이 구성 자체로 의존성 해석은 안 함
        attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME)) // 일반 런타임 사용 속성
    }
}

artifacts {
    archives tasks.named('domainJar')
    domainElements tasks.named('domainJar')
}
