package store._0982.notification.domain;

public enum NotificationType {
    ORDER_SCHEDULED,
    ORDER_COMPLETED,
    ORDER_FAILED,
    SHIPMENT_DEPARTURE,
    SHIPMENT_ARRIVAL,
    POINT_RECHARGED,
    POINT_DEDUCTED,
    POINT_RETURNED,
    DAILY_SETTLEMENT_COMPLETED,
    DAILY_SETTLEMENT_FAILED,
    MONTHLY_SETTLEMENT_COMPLETED,
    MONTHLY_SETTLEMENT_FAILED
}
