#file: noinspection SpellCheckingInspection
spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    store: debug

client:
  commerce: http://localhost:8087

common:
  logging:
    service:
      enabled: true
