spring:
  application:
    name: dummy-data
  main:
    web-application-type: none

dummy-data:
  member-id-pool:
    count: 100000
    path: docs/dummy-data/id-pools/member_id_pool.csv
  product-id-pool:
    count: 1000000
    path: docs/dummy-data/id-pools/product_id_pool.csv
  group-purchase-id-pool:
    count: 1000000
    path: docs/dummy-data/id-pools/group_purchase_id_pool.csv
  order-id-pool:
    count: 1000000
    path: docs/dummy-data/id-pools/order_id_pool.csv
  member-dummy:
    path: docs/dummy-data/dummy-datas/member-dummy.csv
  seller-dummy:
    path: docs/dummy-data/dummy-datas/seller-dummy.csv
  product-dummy:
    path: docs/dummy-data/dummy-datas/product-dummy.csv
  group-purchase-dummy:
    path: docs/dummy-data/dummy-datas/group-purchase-dummy.csv
  order-dummy:
    path: docs/dummy-data/dummy-datas/order-dummy.csv
  canceled-order-dummy:
    path: docs/dummy-data/dummy-datas/canceled-order-dummy.csv
  order-settlement-dummy:
    path: docs/dummy-data/dummy-datas/order-settlement-dummy.csv
  seller-balance-history-dummy:
    path: docs/dummy-data/dummy-datas/seller-balance-history-dummy.csv
  product-vector-dummy:
    path: docs/dummy-data/dummy-datas/product-vector-dummy.csv
  product-vector:
    model-version: dummy-v1
  order:
    group-purchase-count: 100000
  category:
    pet-percent: 20
