#file: noinspection SpellCheckingInspection
name: 'Deploy Private Service'
description: 'Deploy a service to private instance via Bastion proxy'
inputs:
  service-name:
    description: 'Service name (e.g., discovery, search)'
    required: true
  module-name:
    description: 'Gradle module name (defaults to service-name)'
    required: false
  image-name:
    description: 'Docker image name (e.g., minbros/discovery)'
    required: true
  deployment-name:
    description: 'K8s deployment name (defaults to service-name)'
    required: false
  manifest-path:
    description: 'Path to k8s manifest file'
    required: true
  bastion-host:
    description: 'Bastion host address'
    required: true
  bastion-user:
    description: 'Bastion username'
    required: true
  bastion-ssh-key:
    description: 'Bastion SSH key'
    required: true
  private-host:
    description: 'Private host address'
    required: true
  private-user:
    description: 'Private username'
    required: true
  private-ssh-key:
    description: 'Private SSH key'
    required: true
  rollout-timeout:
    description: 'Rollout timeout'
    required: false
    default: '5m'

runs:
  using: 'composite'
  steps:
    - name: JDK 17 설정
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Gradle 실행 권한 부여
      shell: bash
      run: chmod +x ./gradlew

    - name: 버전 태그 생성
      id: version
      shell: bash
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "Image tag: $SHORT_SHA"

    - name: Jib로 Docker 이미지 빌드 (로컬)
      shell: bash
      run: |
        MODULE="${{ inputs.module-name }}"
        if [ -z "$MODULE" ]; then
          MODULE="${{ inputs.service-name }}"
        fi
        ./gradlew :${MODULE}:jibDockerBuild \
          -Djib.to.image=${{ inputs.image-name }} \
          -Djib.to.tags=${{ steps.version.outputs.tag }},latest

    - name: Docker 이미지를 tar 파일로 저장
      shell: bash
      run: |
        docker save ${{ inputs.image-name }}:${{ steps.version.outputs.tag }} | gzip > ${{ inputs.service-name }}.tar.gz
        ls -lh ${{ inputs.service-name }}.tar.gz

    - name: 이미지 파일을 프라이빗 인스턴스로 전송 (Bastion 경유)
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ inputs.private-host }}
        username: ${{ inputs.private-user }}
        key: ${{ inputs.private-ssh-key }}
        port: 22
        source: ${{ inputs.service-name }}.tar.gz
        target: /tmp
        proxy_host: ${{ inputs.bastion-host }}
        proxy_username: ${{ inputs.bastion-user }}
        proxy_key: ${{ inputs.bastion-ssh-key }}
        proxy_port: 22

    - name: SSH로 프라이빗 인스턴스 접속 및 이미지 로드 (Bastion 경유)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ inputs.private-host }}
        username: ${{ inputs.private-user }}
        key: ${{ inputs.private-ssh-key }}
        port: 22
        proxy_host: ${{ inputs.bastion-host }}
        proxy_username: ${{ inputs.bastion-user }}
        proxy_key: ${{ inputs.bastion-ssh-key }}
        proxy_port: 22
        script: |
          echo "Loading Docker image..."
          gunzip -c /tmp/${{ inputs.service-name }}.tar.gz | sudo k3s ctr images import -
          rm -f /tmp/${{ inputs.service-name }}.tar.gz

    - name: K8s 매니페스트 변경 확인
      if: inputs.manifest-path != ''
      id: check-manifest
      shell: bash
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "${{ inputs.manifest-path }}"; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: K8s 매니페스트 파일을 Bastion으로 복사
      if: inputs.manifest-path != '' && steps.check-manifest.outputs.changed == 'true'
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ inputs.bastion-host }}
        username: ${{ inputs.bastion-user }}
        key: ${{ inputs.bastion-ssh-key }}
        port: 22
        source: ${{ inputs.manifest-path }}
        target: /tmp/k8s-${{ inputs.service-name }}-temp
        strip_components: 3
        overwrite: true

    - name: K8s 리소스 적용
      if: inputs.manifest-path != '' && steps.check-manifest.outputs.changed == 'true'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ inputs.bastion-host }}
        username: ${{ inputs.bastion-user }}
        key: ${{ inputs.bastion-ssh-key }}
        port: 22
        command_timeout: '3m'
        script: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          MANIFEST_FILE=$(basename "${{ inputs.manifest-path }}")
          echo "Applying $MANIFEST_FILE..."
          kubectl apply -f /tmp/k8s-${{ inputs.service-name }}-temp/$MANIFEST_FILE
          echo "${{ inputs.service-name }} manifest applied successfully"
          rm -rf /tmp/k8s-${{ inputs.service-name }}-temp

    - name: 컨트롤 플레인 접속 후 배포 명령 실행
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ inputs.bastion-host }}
        username: ${{ inputs.bastion-user }}
        key: ${{ inputs.bastion-ssh-key }}
        port: 22
        script: |
          DEPLOYMENT="${{ inputs.deployment-name }}"
          if [ -z "$DEPLOYMENT" ]; then
            DEPLOYMENT="${{ inputs.service-name }}"
          fi

          echo "Updating deployment..."
          kubectl set image deployment/$DEPLOYMENT \
            $DEPLOYMENT=${{ inputs.image-name }}:${{ steps.version.outputs.tag }} \
            --kubeconfig=/etc/rancher/k3s/k3s.yaml

          echo "Waiting for rollout..."
          kubectl rollout status deployment/$DEPLOYMENT \
            --timeout=${{ inputs.rollout-timeout }} \
            --kubeconfig=/etc/rancher/k3s/k3s.yaml

          echo "${{ inputs.service-name }} Server deployed successfully with version ${{ steps.version.outputs.tag }}"
