#file: noinspection HttpUrlsUsage, SpellCheckingInspection
spring:
  application:
    name: elastic-search

  jackson:
    time-zone: Asia/Seoul

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 0.0
    propagation:
      type: w3c  # 또는 b3

kafka:
  bootstrap-servers: ${spring.kafka.bootstrap-servers}

logging:
  level:
    org.apache.kafka: warn
    org.springframework.kafka: warn
